config/routes.rb
Rails.application.routes.draw do
  
  # --- API ------------------------------------
  
  namespace :api_v1 do
    resources :procedures do
      member do
        get :arguments_combined
      end
    end
  end
  
  # --- WEB ------------------------------------
  
  resources :exports
  
  resources :receipts
  get 're/:id' => 'receipts#edit', as: 'answer_receipt'
  
  resources :ratings do
    member do
      put :relay
    end
  end
  get 'ra/:id' => 'ratings#answer', as: 'answer_rating'
  
  resources :follows
  
  resources :favs
  
  resources :comments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :ratings
  end
  
  resources :arguments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :comments
    resources :ratings
  end
  
  resources :attachments
  
  resources :procedures do
    member do
      put :activate
      put :approve
      get :intro_what
      get :intro_views
      get :intro_actions
      get :vote
      get :result
      get :embed
    end
    
    resources :attachments
    resources :arguments
    resources :follows
    
    resources :receipts
    
    resources :exports
  end
  
  resources :periods
  
  resources :bodies do
    member do
      get :graph
    end
    
    resources :procedures do
      collection do
        get :coming
        get :most_contributed
        get :most_faved
      end
    end
    resources :subjectgroups do
      resources :procedures
    end
  end
  
  resources :moderatorships
  
  resources :visitors do
    member do
      put :send_confirmation
      get :confirm
    end
    
    resource :account
    resources :arguments
    resources :comments
    resources :favs
    resources :follows
    resources :ratings
  end
  get 'lo/:id' => 'visitors#login', as: 'login_visitor'
  
  resources :accounts do
    member do
      get :set_password
    end
  end
  
  controller :info do
    get 'info/impressum', to: redirect( 'https://gremien.teilt-mit.de/info/impressum' )
    get 'info/datenschutz', to: redirect( 'https://gremien.teilt-mit.de/info/datenschutz' )
    get 'info/details', to: redirect( 'https://gremien.teilt-mit.de/info/details' )
    
    get :cockpit
    get :history
    get :approval
    get :contribution_rules
    get :why
    put :close_dialog
    get 'info/tick_moderation' => 'info#tick_moderation'
    
    get 'info/logs' => 'info#logs'
    
    get 'info/:id' => :show
  end
  
  
  
  # --- Login / Logout Requests ----------------
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  put '/reset_password', to: 'accounts#reset_password'
  
  # --- Log ------------------------------------
  
  resources :logs
  
  # Redirect existing gremieninfo posts
  get '/posts/:id', to: redirect( "https://gremien.teilt-mit.de/posts/%{id}" )
  
  # Redirect unsubscriptions tu gremien.teilt-mit.de
  get '/newssubscriptions/*other', to: redirect { |pp, req| req.original_url.to_s.gsub( '//teilt', '//gremien.teilt' ) }
  
  get '/help', to: 'application#help'
  
  get '/logout', to: 'application#logout'
  
  root to: 'application#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/bodies_helper.rb
module BodiesHelper
  
  def h_new_procedure_path
    if @body
      new_body_procedure_path( @body )
    else
      new_procedure_path
    end
  end
  
  def h_body_procedures_for_account( in_body )
    result = []
    result |= in_body.procedures.owned_by?( current_account ).sorted if current_account
    result |= in_body.procedures.opened.published.sorted
    return result
  end
  
  def h_body_selected_class( in_body )
    @body == in_body ? 'selected' : nil
  end
  
end

app/views/bodies/_bodies_list.html.haml
%ul.entities_list.bodies_list
  - @bodies.each do |body|
    %li{ id: body.iid, class: h_body_selected_class( body ) }
      = link_to body, class: 'preview' do
        .title
          = body.name
        
        .description
          = h_markdown_strip body.description, 250
        
        .infos
          =t '.active_procedures'
          %span.vignette= body.procedures.opened.published.size
        
      
    
  

app/views/bodies/_proc_selector_status.html.haml
%li.procedure_selector
  = link_to body_procedures_path( @body, current_status: status.current_status ), class: 'preview' do
    = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
    .count.vignette= status.count
    .status= status.current_status || 'unbekannt'
  

app/views/bodies/_proc_selector_subjectgroup.html.haml
%li.procedure_selector
  = link_to body_subjectgroup_procedures_path( @body, subjectgroup ), class: 'preview' do
    = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
    .count.vignette= subjectgroup.count
    .status= subjectgroup.title
  

app/views/bodies/_procedure_block.html.haml
%li.procedure_block{ id: procedure.iid, title: procedure.title_short, data: { typ: procedure.proc_type_selector_id, cst: procedure.current_status_selector_id, sug: procedure.subjectgroups_ids, tag: procedure.tags_ids } }
  - if procedure.current_status
    .status{ class: "cst_#{procedure.current_status_selector_id}" }
      = procedure.current_status[ 0 ]
    
  
  .procedure_mini
    .text
      .title= procedure.title_short
    
    .attachments{ class: procedure.proc_type.to_s.parameterize }
      - procedure.attachments.each do |att|
        = image_tag "sym/document_#{procedure.proc_type.to_s.parameterize}.svg"
      
    
  
  .procedure_dialog_detail
    = link_to procedure, target: '_blank' do
      .text
        .type= procedure.proc_type
        .title= procedure.title
        .abstract= truncate procedure.abstract, length: 800
        .info
          .date
            eingereicht am
            =l procedure.submission_at, format: :short_day
          
          - if procedure.last_change_at
            .date
              letzte Änderung am
              =l procedure.last_change_at, format: :short_day
            
          
          .proc_current_status{ class: "cst_#{procedure.current_status_selector_id}" }= procedure.current_status
        
      
    
    .attachments
      - procedure.attachments.each do |att|
        = link_to image_tag( "sym/document_#{procedure.proc_type.to_s.parameterize}.svg" ), procedure, target: '_blank', title: att.title
      
    
    = render 'procedures/arguments_vignette', procedure: procedure
  

app/views/bodies/_selectors.html.haml
%aside.selectors.groups
  .selector_list_title Typ
  %ul.selector_list
    - @all_proc_types.each do |type|
      %li.selector{ title: type.proc_type, data: { sel_key: 'typ', sel_id: Procedure.get_selector_id( type.proc_type ) } }
        .count= type.count
        .title= type.proc_type
      
    
  
  .selector_list_title Status
  %ul.selector_list
    - @all_current_status.each do |status|
      %li.selector{ title: status.current_status, data: { sel_key: 'cst', sel_id: Procedure.get_selector_id( status.current_status ) } }
        .count= status.count
        .title= status.current_status
      
    
  
  .selector_list_title Themengebiete
  %ul.selector_list
    - @subjectgroups.each do |subjectgroup|
      %li.selector{ title: subjectgroup.title, data: { sel_key: 'sug', sel_id: subjectgroup.id } }
        .count= subjectgroup.procedures.count
        .title= subjectgroup.title
      
    
  

%aside.selectors.tags
  .selector_list_title Stichworte
  %ul.selector_list.searchable
    - @tags.each do |tag|
      %li.selector{ title: tag.key, data: { sel_key: 'tag', sel_id: tag.id } }
        .count= tag.procedures.count
        .title= tag.key
      
    
  

app/views/bodies/graph.html.haml
- h_title "Graph Gremium '#{@body.name}'"
- h_description "Grafische Übersicht über alle Vorhaben des #{@body.name}"
- h_titlebar_icon 'back_arrow', bodies_path
- h_titlebar_text @body.name

.dialog_layer.procedure_graph.prepared
  .dialog_outer
    .dialog
    
  

%section.graph
  = render 'selectors'
  
  .search_block
    = search_field_tag 'search', nil, placeholder: 'Suchbegriff...'
  
  %ul.procedures_graph
    - @group_keys.each do |key|
      - group = @groups[ key ]
      %li.sort_separator= group.first.last_change_at ? l( group.first.last_change_at, format: :month_year ) : 'unbekannt'
      
      = render partial: 'procedure_block', collection: group.sort_by { |p| p.last_change_at ? p.last_change_at : nil }.reverse, as: :procedure, cached: true
    
  

app/views/bodies/index.html.haml
- h_title 'Liste der Gremien'
- h_titlebar_text t( '.bodies' )
- h_titlebar_icon_text 'Startseite'

%section.bodies
  = render 'bodies_list', bodies: @bodies

%section.procedures
  = render 'procedures/index', procedures: h_body_procedures_for_account( @bodies.first )

app/views/bodies/show.html.haml
- h_title "Gremium: #{@body.name}"
- h_description @body.description
- h_titlebar_icon 'back_arrow', bodies_path, 'Alle Gremien'
- h_titlebar_text @body.name

%section.bodies
  = render 'bodies_list', bodies: @bodies

%section.body
  .title
    Ausgewählte Vorhaben
    = 'des' unless @body.none?
    %strong= @body.name
  
  .description= h_markdown @body.description
  
  - unless @body.none?
    .info
      Weitere Informationen zu diesem Gremium unter
      = link_to @body.url, @body.url
    
  

%section.procedures
  %ul.entities_list.procedures_list
    %li.entity_action_new
      = link_to 'Neues Vorhaben...', h_new_procedure_path, class: 'button'
      %p.help Bringen Sie ein neues Vorhaben zur Mitwirkung ein
    
    - h_body_procedures_for_account( @body ).each do |procedure|
      - cache_unless ( h_faved?( procedure ) or h_dissed?( procedure ) ), procedure do
        = render 'procedures/proc_list_preview', procedure: procedure
      
    
  

app/views/bodies/show_bt.html.haml
- h_title "Vorhaben #{@body.name}"
- h_description @body.description
- h_titlebar_icon 'back_arrow', bodies_path
- h_titlebar_text @body.name

%section.body.bundestag
  .title
    Alle Vorhaben des
    %strong= @body.name
  
  .description= h_markdown @body.description
  
  .info
    Weitere Informationen zu diesem Gremium unter
    = link_to @body.url, @body.url
  

%section.selectors_lists.bundestag
  .entity_action_graph
    = link_to graph_body_path( @body ) do
      = image_tag 'body_graph.png'
      %br
      Grafische Übersicht über alle Vorhaben&nbsp;&rarr;
    
  
  .lists_first
    %ul.entities_list.selectors_list.general
      %li.procedure_selector_title Listen
      %li.procedure_selector
        = link_to coming_body_procedures_path( @body ), class: 'preview' do
          = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
          .count.vignette.attention= @body.deals_coming.count
          .status Demnächst im Plenum
        
      
      %li.procedure_selector
        = link_to most_contributed_body_procedures_path( @body ), class: 'preview' do
          = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
          .count.vignette.hilite= @body.proc_most_contributed.count
          .status Meistdiskutiert
        
      
      %li.procedure_selector
        = link_to most_faved_body_procedures_path( @body ), class: 'preview' do
          = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
          .count.vignette.hilite= @body.proc_most_faved.count
          .status Meistbewertet
        
      
      %li.procedure_selector
        = link_to body_procedures_path( @body ), class: 'preview' do
          = image_tag 'sym/angle_right_s50.svg', class: 'arrow_icon'
          .count.vignette= @body.procedures.published.opened.count
          .status Alle Vorhaben
        
      
    
    %ul.entities_list.selectors_list.status
      %li.procedure_selector_title Listen nach Status
      = render partial: 'proc_selector_status', collection: @all_current_status, as: :status
      
    
  
  .lists_second
    %ul.entities_list.selectors_list.subjectgroups
      %li.procedure_selector_title Listen nach Themengebiet
      = render partial: 'proc_selector_subjectgroup', collection: @all_subjectgroups, as: :subjectgroup
      
    
  