config/routes.rb
Rails.application.routes.draw do
  
  # --- API ------------------------------------
  
  namespace :api_v1 do
    resources :procedures do
      member do
        get :arguments_combined
      end
    end
  end
  
  # --- WEB ------------------------------------
  
  resources :exports
  
  resources :receipts
  get 're/:id' => 'receipts#edit', as: 'answer_receipt'
  
  resources :ratings do
    member do
      put :relay
    end
  end
  get 'ra/:id' => 'ratings#answer', as: 'answer_rating'
  
  resources :follows
  
  resources :favs
  
  resources :comments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :ratings
  end
  
  resources :arguments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :comments
    resources :ratings
  end
  
  resources :attachments
  
  resources :procedures do
    member do
      put :activate
      put :approve
      get :intro_what
      get :intro_views
      get :intro_actions
      get :vote
      get :result
      get :embed
    end
    
    resources :attachments
    resources :arguments
    resources :follows
    
    resources :receipts
    
    resources :exports
  end
  
  resources :periods
  
  resources :bodies do
    member do
      get :graph
    end
    
    resources :procedures do
      collection do
        get :coming
        get :most_contributed
        get :most_faved
      end
    end
    resources :subjectgroups do
      resources :procedures
    end
  end
  
  resources :moderatorships
  
  resources :visitors do
    member do
      put :send_confirmation
      get :confirm
    end
    
    resource :account
    resources :arguments
    resources :comments
    resources :favs
    resources :follows
    resources :ratings
  end
  get 'lo/:id' => 'visitors#login', as: 'login_visitor'
  
  resources :accounts do
    member do
      get :set_password
    end
  end
  
  controller :info do
    get 'info/impressum', to: redirect( 'https://gremien.teilt-mit.de/info/impressum' )
    get 'info/datenschutz', to: redirect( 'https://gremien.teilt-mit.de/info/datenschutz' )
    get 'info/details', to: redirect( 'https://gremien.teilt-mit.de/info/details' )
    
    get :cockpit
    get :history
    get :approval
    get :contribution_rules
    get :why
    put :close_dialog
    get 'info/tick_moderation' => 'info#tick_moderation'
    
    get 'info/logs' => 'info#logs'
    
    get 'info/:id' => :show
  end
  
  
  
  # --- Login / Logout Requests ----------------
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  put '/reset_password', to: 'accounts#reset_password'
  
  # --- Log ------------------------------------
  
  resources :logs
  
  # Redirect existing gremieninfo posts
  get '/posts/:id', to: redirect( "https://gremien.teilt-mit.de/posts/%{id}" )
  
  # Redirect unsubscriptions tu gremien.teilt-mit.de
  get '/newssubscriptions/*other', to: redirect { |pp, req| req.original_url.to_s.gsub( '//teilt', '//gremien.teilt' ) }
  
  get '/help', to: 'application#help'
  
  get '/logout', to: 'application#logout'
  
  root to: 'application#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/visitors/_form.html.haml
= form_for visitor do |f|
  - if visitor.errors.any?
    #error_explanation
      %h2
        = visitor.errors.count
        Fehler verhinderten, dass der Besucher ergänzt wurde.
      
      %ul
        - visitor.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.label :email, 'E-Mail-Adresse'
    = render 'general/email_usage'
    = f.email_field :email, autofocus: true, placeholder: 'hanna@muster.de'
  
  .actions
    = f.submit 'Speichern', class: 'button'
  

app/views/visitors/confirm.html.haml
- h_title "Fehler: Link abgelaufen"
- h_description 'Meine Besucher-Seite'
- h_titlebar_text 'Fehler'


.small_content
  %h4 Fehler: Link ungültig!
  %p
    Der Link, den sie benutzt haben, ist leider ungültig oder abgelaufen.
  
  %p
    Klicken Sie, um einen neuen Link an Ihre E-Mail Adresse anzufordern.
  
  %p
    - if @visitor
      = link_to 'Link anfordern', send_confirmation_visitor_path( @visitor ), method: :put, class: 'button'
    - else
      = link_to 'E-Mail eingeben', login_path, class: 'button'
    
  

app/views/visitors/edit.html.haml
- h_title 'Besucher ergänzen'
- h_titlebar_text 'E-Mail ergänzen'

.entity_form
  .form_explanation
    Bitte geben Sie Ihre E-Mail-Adresse an
  
  = render 'form', visitor: @visitor
  
  .form_cancel= link_to 'Abbrechen', root_path, class: 'button cancel'

app/views/visitors/new.html.haml
%h1 New visitor

= render 'form', visitor: @visitor

= link_to 'Back', visitors_path

app/views/visitors/send_confirmation.html.haml
- h_title "Bestätigungslink gesendet"
- h_description 'Meine Besucher-Seite'
- h_titlebar_text 'Link gesendet'


.small_content
  %h4 Link zur Bestätigung gesendet
  %p
    Bitte schauen Sie in Ihrem E-Mail Postfach oder im Spam-Filter.
  

app/views/visitors/show.html.haml
- h_title "Besucher: Meine Daten"
- h_description 'Meine Besucher-Seite'
- h_titlebar_icon 'back_arrow', bodies_path
- h_titlebar_text 'Meine Daten'


- unless h_visitor_saw? 'visitor_me_intro'
  - content_for :dialog_content do
    %p
      Herzlich Willkommen!
    
    %p
      Auf der Seite
      %strong Meine Daten
      halten wir alle Ihre Beiträge für Sie
      - if h_visitor_has_email?
        zusammen.
      - else
        zusammen, solange Sie unseren
        %strong Cookie im Browser nicht löschen.
      
    
    %p
      Sie finden Sie immer
      %strong links oben unter Menu.
    
    - unless h_visitor_has_email?
      %p
        Wenn Sie Ihre Beiträge
        %strong dauerhaft sichern
        wollen, teilen Sie uns bitte eine E-Mail mit, wir senden dann einen
        %strong Bestätigungslink.
      
    
  
  - content_for :dialog_actions do
    = link_to 'Ok, danke', close_dialog_path( saw: 'visitor_me_intro' ), remote: true, method: :put, 'data-turbolinks': false, class: 'button'
  
  = render 'general/dialog'


%section.me
  .details
    %h3.title Anonyme/r BesucherIn
    .status
      - case
      - when @visitor.confirmed?
        E-Mail bestätigt:
        %strong= @visitor.email
        &nbsp;&nbsp;
        = link_to t( '.not_me' ), logout_path, class: 'link'
        %br
        = link_to 'Eigenes Kennwort festlegen', new_visitor_account_path( @visitor ), class: 'action'
        
      - when h_visitor_has_email?
        %strong vorläufig unbestätigt:
        = @visitor.email
        &nbsp;&nbsp;
        = link_to t( '.not_me' ), logout_path, class: 'link'
        %br
        .message_important
          Bitte schauen Sie nach Ihrer E-Mail-Bestätigung...&nbsp;&nbsp;
          = link_to 'nochmal senden', send_confirmation_visitor_path( @visitor ), method: :put
        
      - else
        .bad ungesichtert, verfällt
      
    
  
  = render 'form', visitor: @visitor unless h_visitor_has_email?

- unless @visitor.arguments.blank?
  %section.arguments
    = render 'general/entities_list', entities: @visitor.arguments.by_recent, entity_name: 'Argument' + ( @visitor.confirmed? ? '' : ' ungesichert' )
  

- unless @visitor.comments.blank?
  %section.comments
    = render 'general/account_comments_list', comments: @visitor.comments.by_recent
  

- unless @visitor.favs.blank?
  %section.favs
    = render 'favs/list', favs: @visitor.favs.by_recent
  

- unless @visitor.follows.blank?
  %section.follows
    = render 'follows/list', follows: @visitor.follows.by_recent
  