config/routes.rb
Rails.application.routes.draw do
  
  # --- API ------------------------------------
  
  namespace :api_v1 do
    resources :procedures do
      member do
        get :arguments_combined
      end
    end
  end
  
  # --- WEB ------------------------------------
  
  resources :exports
  
  resources :receipts
  get 're/:id' => 'receipts#edit', as: 'answer_receipt'
  
  resources :ratings do
    member do
      put :relay
    end
  end
  get 'ra/:id' => 'ratings#answer', as: 'answer_rating'
  
  resources :follows
  
  resources :favs
  
  resources :comments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :ratings
  end
  
  resources :arguments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :comments
    resources :ratings
  end
  
  resources :attachments
  
  resources :procedures do
    member do
      put :activate
      put :approve
      get :intro_what
      get :intro_views
      get :intro_actions
      get :vote
      get :result
      get :embed
    end
    
    resources :attachments
    resources :arguments
    resources :follows
    
    resources :receipts
    
    resources :exports
  end
  
  resources :periods
  
  resources :bodies do
    member do
      get :graph
    end
    
    resources :procedures do
      collection do
        get :coming
        get :most_contributed
        get :most_faved
      end
    end
    resources :subjectgroups do
      resources :procedures
    end
  end
  
  resources :moderatorships
  
  resources :visitors do
    member do
      put :send_confirmation
      get :confirm
    end
    
    resource :account
    resources :arguments
    resources :comments
    resources :favs
    resources :follows
    resources :ratings
  end
  get 'lo/:id' => 'visitors#login', as: 'login_visitor'
  
  resources :accounts do
    member do
      get :set_password
    end
  end
  
  controller :info do
    get 'info/impressum', to: redirect( 'https://gremien.teilt-mit.de/info/impressum' )
    get 'info/datenschutz', to: redirect( 'https://gremien.teilt-mit.de/info/datenschutz' )
    get 'info/details', to: redirect( 'https://gremien.teilt-mit.de/info/details' )
    
    get :cockpit
    get :history
    get :approval
    get :contribution_rules
    get :why
    put :close_dialog
    get 'info/tick_moderation' => 'info#tick_moderation'
    
    get 'info/logs' => 'info#logs'
    
    get 'info/:id' => :show
  end
  
  
  
  # --- Login / Logout Requests ----------------
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  put '/reset_password', to: 'accounts#reset_password'
  
  # --- Log ------------------------------------
  
  resources :logs
  
  # Redirect existing gremieninfo posts
  get '/posts/:id', to: redirect( "https://gremien.teilt-mit.de/posts/%{id}" )
  
  # Redirect unsubscriptions tu gremien.teilt-mit.de
  get '/newssubscriptions/*other', to: redirect { |pp, req| req.original_url.to_s.gsub( '//teilt', '//gremien.teilt' ) }
  
  get '/help', to: 'application#help'
  
  get '/logout', to: 'application#logout'
  
  root to: 'application#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/procedures_helper.rb
module ProceduresHelper
  
  def h_editable?( in_procedure )
    #logger.debug "-- current_account:#{current_account}"
    current_account and in_procedure.editable_by? current_account
  end
  
  def h_for_body?( in_procedure )
    in_procedure.body.id != 1
  end
  
  def h_faved?( in_entity )
    current_visitor? and in_entity.faved_by?( current_visitor ) and in_entity.fav_for( current_visitor ).up?
  end
  def h_dissed?( in_entity )
    current_visitor? and in_entity.faved_by?( current_visitor ) and in_entity.fav_for( current_visitor ).down?
  end
  
  def h_followed?( in_entity )
    current_visitor? and in_entity.followed_by? current_visitor
  end
  
  def h_args( in_procedure, in_kind = 'info' )
    args_kind = in_procedure.arguments.send( in_kind )
    result = []
    result |= args_kind.owned_by?( current_visitor ) if current_visitor?
    result |= args_kind.rate_by?( current_visitor ) if current_visitor?
    
    result |= args_kind.published
    result |= args_kind.moderating.select { |a| a.accepted? }
    
    result.sort_by! { |a| a.favs_sum }
        .reverse!
    return result
  end
  
  def h_comments( in_comments )
    result = []
    result |= in_comments.owned_by?( current_visitor ) if current_visitor?
    result |= in_comments.rate_by?( current_visitor ) if current_visitor?
    
    result |= in_comments.published
    result |= in_comments.moderating.select { |c| c.accepted? }
    
    result.sort_by! { |c| c.favs_sum }
        .reverse!
    return result
  end
  
end

app/views/procedures/_fav_display.html.haml
.fav_display{ id: "fav_display_#{entity.iid}" }
  - faved = h_faved?( entity )
  - dissed = h_dissed?( entity )
  
  - if entity.favs.up.size > 0
    = image_tag "sym/arrow_up_#{ faved ? 'blue_fill' : 'gray' }.svg", class: 'vignette_sym'
    .vignette_text{ class: faved ? 'hilite' : nil }
      = entity.favs.up.size
    
  
  - if entity.favs.down.size > 0
    = image_tag "sym/arrow_down_#{ dissed ? 'blue_fill' : 'gray' }.svg", class: 'vignette_sym'
    .vignette_text{ class: dissed ? 'hilite' : nil }
      = entity.favs.down.size
    
  

app/views/procedures/_form_s1.html.haml
- first = h_partial_init first, false

= form_for procedure do |f|
  - if procedure.errors.any?
    #error_explanation
      %h2
        = procedure.errors.count
        Fehler!
        %br
        Mitwirkungsforum kann nicht angelegt werden.
      
      %ul
        - procedure.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    .form_explanation Wer darf bei dem Vorhaben mitwirken?
    = f.radio_button :kind, :open
    = f.label :kind, "<strong>Öffentlich:</strong> jeder kann mitwirken".html_safe, value: :open
    %br
    = f.radio_button :kind, :link
    = f.label :kind, "<strong>Gruppe:</strong> nur mit speziellem Link".html_safe, value: :link
    - if false
      %br
      = f.radio_button :kind, :account
      = f.label :kind, "<strong>Ausgewählte:</strong> nur mit E-Mail Einladung".html_safe, value: :account
    
  
  %br
  .field
    = f.label :title, 'Um was geht es in dem Vorhaben?'
    = f.text_field :title, autofocus: true, placeholder: 'Kurze Zusammenfassung in einem Satz'
  
  .actions
    = f.submit t( 'actions.save' ), class: 'button'
  

app/views/procedures/_form_s3.html.haml
- first = h_partial_init first, false

%h5 Schritt 3: Terminierung

= form_for procedure do |f|
  - if procedure.errors.any?
    #error_explanation
      %h2
        = procedure.errors.count
        Fehler verhindern, dass dieses Mitwirkungsforum erzeugt werden kann:"
      %ul
        - procedure.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field.datetime
    = f.label :submission_at, 'Wann wurde das Vorhaben eingereicht?'
    = f.date_select :submission_at
  
  .field.datetime
    = f.label :vote_date_at, 'Ab wann darf über das Vorhaben abgestimmt werden?'
    = f.datetime_select :vote_date_at
  
  .field.datetime
    = f.label :vote_end_at, 'Bis wann darf über das Vorhaben abgestimmt werden?'
    = f.datetime_select :vote_end_at
  
  .actions
    = f.submit t( 'actions.save' ), class: 'button'
  

app/views/procedures/_form_s5.html.haml
- first = h_partial_init first, false

%h5 Schritt 5: ModeratorInnen

= render 'moderatorships/list', moderatorships: procedure.moderatorships

= form_for procedure do |f|
  - if procedure.errors.any?
    #error_explanation
      %h2
        = procedure.errors.count
        Fehler verhindern, dass dieses Mitwirkungsforum erzeugt werden kann:"
      %ul
        - procedure.errors.full_messages.each do |message|
          %li= message
        
      
    
  .field
    = f.label :mod_email, "Liste #{procedure.moderatorships.size > 0 ? ' weitere' : ''} E-Mail Adressen"
    = f.text_area :mod_emails, rows: 5, placeholder: 'E-Mail Adressen eingeben, getrennt durch Komma oder Leerzeichen...'
  
  .actions
    = f.submit t( 'actions.save' ), class: 'button'
  

app/views/procedures/_show_arguments.html.haml
- new_tab = h_partial_init new_tab, false
- # --------------------------------------------
- target = new_tab ? '_blank' : nil
- pros = h_args( procedure, 'pro' )
- infos = h_args( procedure, 'info' )
- contras = h_args( procedure, 'contra' )

- active_column = 'info'
- if infos.size < 1
  - active_column = 'contra' if contras.size > 0
  - active_column = 'pro' if pros.size > 0 and pros.size >= contras.size


%nav.arguments_nav
  .nav_column.pro{ class: active_column == 'pro' ? 'active' : nil, data: { kind: 'pro' } }
    = pros.size
    =t 'labels.pro'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'pro' ), class: 'button_plus', target: target
  
  .nav_column.info{ class: active_column == 'info' ? 'active' : nil, data: { kind: 'info' } }
    = infos.size
    =t 'labels.info'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'info' ), class: 'button_plus', target: target
  
  .nav_column.contra{ class: active_column == 'contra' ? 'active' : nil, data: { kind: 'contra' } }
    = contras.size
    =t 'labels.contra'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'contra' ), class: 'button_plus', target: target
  

.arguments_columns
  .arguments_column.pro{ class: active_column == 'pro' ? 'active' : nil, data: { kind: 'pro' } }
    - if pros.blank?
      .help=t '.new_pro_arg'
    - else
      = render 'arguments/arguments_list', arguments: pros
  
  .arguments_column.info{ class: active_column == 'info' ? 'active' : nil, data: { kind: 'info' } }
    - if infos.blank?
      .help=t '.new_info_arg'
    - else
      = render 'arguments/arguments_list', arguments: infos
  
  .arguments_column.contra{ class: active_column == 'contra' ? 'active' : nil, data: { kind: 'contra' } }
    - if contras.blank?
      .help=t '.new_contra_arg'
    - else
      = render 'arguments/arguments_list', arguments: contras
  

app/views/procedures/activate.html.haml
- h_title 'Vorhaben aktiviert'
- h_titlebar_icon 'back_arrow', @procedure
- h_titlebar_text 'Aktivierung'

.entity_form.centered
  %h4 Vorhaben ist aktiviert!
  
  - if @procedure.group_moderation?
    %p
      Wir haben die angegebenen
      = @procedure.moderators.size
      ModeratorInnen informiert
      %br
      und um Bestätigung gebeten.
    
  
  - if @procedure.kind == 'link'
    %p
      Mitwirkende finden Ihr Vorhaben
      %strong nicht
      in den Listen,
      %br
      sondern
      %strong nur über diesen Link
      hier:
    
    %p.procedure_link
      = procedure_url @procedure
    
  
  .actions
    = link_to 'Weiter', @procedure, class: 'button'
  

app/views/procedures/coming.html.haml
- h_title 'Liste ' + @titlebar_text
- h_description @page_description
- h_titlebar_icon 'back_arrow', @body
- h_titlebar_text @titlebar_text

.procedure_selector_title
  .vignette= @deals.size
  demnächst im Bundestag behandelte Vorhaben
  .help sortiert nach Datum

%ul.entities_list.deals_list
  - @deals.each do |deal|
    = render 'procedures/deal_coming_preview', deal: deal
  

app/views/procedures/destroy.js.erb
$( '#<%= @procedure_iid %>' ).hide( 500 );

app/views/procedures/intro_actions.html.haml
- h_title "Intro zu Vorhaben - Aktionen"
- h_description @procedure.description
- h_titlebar_icon 'back_arrow', bodies_path
- h_titlebar_text 'Vorhaben'

%section.intro_actions
  %ul.actions_list
    %li.action
      .actions= link_to t( 'actions.subscribe' ), '#'
      .description
        %p Folgen Sie einem Vorhaben, wenn Sie Benachrichtigungen bei neuen Beiträgen oder zur Abstimmung bekommen wollen.
      
    
    %li.action
      .actions= link_to t( 'actions.share' ), '#'
      .description
        %p Leiten Sie ein Vorhaben weiter, wenn Sie eine E-Mail mit diesem Vorhaben und der URL dazu an jemand anderen senden wollen.
      
    
    %li.action
      .actions= link_to t( 'actions.fav' ), '#'
      .description
        %p
          Favorisieren Sie ein Vorhaben/ Argument/ Kommentar, um es als wichtig zu kennzeichnen.
        
        %p
          Damit steigt es in der Liste der Vorhaben/ Argumente/ Kommentare nach oben.
      
    
    %li.action
      .vignette 2
      .vignette.hilite 3
      .description
        %p
          Die Zahlen im Kreis geben an, wieviele Menschen schon favorisiert/ kommentiert haben.
        %p
          Ist der Kreis blau, haben Sie selbst auch favorisiert/ kommentiert.
        
      
    
    %li.action
      .actions
        = link_to image_tag( 'sym/plus_w100.svg' ), '#', class: 'button_plus'
      
      .description
        %p
          Schreiben Sie ein neues Argument für oder gegen das Vorhaben oder formulieren Sie eine neue Information zum Vorhaben.
        
      
    
    %li.action
      .actions= link_to t( 'actions.comment' ), '#'
      .description
        %p
          Schreiben Sie einen Kommentar zu einem Argument, wenn Sie etwas ergänzen oder zur Formulierung kritisieren möchten.
      
    
  
  .dialog.embedded
    .dialog_content
      %p
        Die Aktionen:
      
      %p
        Hier sehen Sie, welche Funktionen sie hier nutzen können.
      
    
    .dialog_actions
      = link_to 'Weiter', @procedure, class: 'button'
    
  

app/views/procedures/intro_views.html.haml
- h_title "Intro zu Vorhaben - Anzeige"
- h_description @procedure.description
- h_titlebar_icon 'back_arrow', bodies_path
- h_titlebar_text t( 'labels.procedure' )

%section.procedure
  .preview
    .title Titel
    .text#procedure_text
      .description.markdown_content
        Beschreibung des Vorhabens
      
      .url= link_to 'Link zu mehr Infos &rarr;'.html_safe, '#'
      
    .expander_text{ data: { sel: '#procedure_text', action: 'text_expand' } }
      = image_tag 'sym/expander_s50.svg', class: 'expander'
      = image_tag 'sym/collapser_s50.svg', class: 'collapser'
    
    .intro_views
      .dialog.embedded
        .dialog_content
          %p
            Die Bereiche:
          
          %p
            Was an welcher Stelle steht.<br/>
            Klicken Sie z.B. den Aufklapper oder die weissen Argument-Karten
            
          
        
        .dialog_actions
          = link_to 'Weiter', intro_actions_procedure_path( @procedure ), class: 'button'
        
      
    
  
  .attachments
    .attachments_list_title
      Weitere Dokumente zum Vorhaben
    
    %ul.attachments_list
      %li
        = link_to '#', class: 'attachment', target: '_blank' do
          = image_tag 'sym/document_s100.svg', class: 'icon'
          Eine Datei
        
      
      %li
        = link_to '#', class: 'attachment', target: '_blank' do
          = image_tag 'sym/document_s100.svg', class: 'icon'
          Noch eine Datei
        
      
    
  

%section.all_arguments
  %nav.arguments_nav
    .nav_column.pro{ data: { kind: 'pro' } }
      Pro
    
    .nav_column.info.active{ data: { kind: 'info' } }
      Infos
    
    .nav_column.contra{ data: { kind: 'contra' } }
      Contra
    
  
  .arguments_columns
    .arguments_column.pro{ data: { kind: 'pro' } }
      %ul.arguments_list
        %li.argument_preview.collapsed
          .title Titel des Pro-Arguments
          .description Beschreibung dazu
          %ul.comments_list
            %li.comment
              Text eines Kommentares
            
          
        
        %li.argument_preview.collapsed
          .title Titel des Pro-Arguments
          .description Beschreibung dazu
        
      
    
    .arguments_column.info.active{ data: { kind: 'info' } }
      %ul.arguments_list
        %li.argument_preview.collapsed
          .title Titel der Information
          .description Beschreibung dazu
          
          %ul.comments_list
            %li.comment
              Text eines Kommentares
            
            %li.comment
              Text eines Kommentares
            
          
        
      
    
    .arguments_column.contra{ data: { kind: 'contra' } }
      %ul.arguments_list
        %li.argument_preview.collapsed
          .title Titel des Contra-Arguments
          .description Beschreibung dazu
          
          %ul.comments_list
            %li.comment
              Text eines Kommentares
            
          
        
      
    
  

app/views/procedures/not_votable.html.haml
- h_title 'Ihre Stimme'
- h_titlebar_icon 'back_arrow', @procedure
- h_titlebar_text 'Ihre Stimme'

.entity_form
  %h4 Keine Abstimmung möglich
  %p
    Zu diesem Vorhaben ist keine Abstimmung vorgesehen.
  
  .form_cancel
    = link_to 'Abbrechen', @procedure, class: 'button cancel'
  

app/views/procedures/not_vote_ready.html.haml
- h_title 'Ihre Stimme'
- h_titlebar_icon 'back_arrow', @procedure
- h_titlebar_text 'Ihre Stimme'

.entity_form
  %h4 Abstimmung noch nicht geöffnet
  %p
    Der Zeitpunkt zur Abstimmung ist
    %strong noch nicht erreicht.
    Im Moment läuft nur die Debatte dazu.
  
  %p
    Die Abstimmung ist
    %strong
      ab dem
      =l @procedure.vote_date_at
    möglich.
  
  - if current_visitor? and !@follow.new_record?
    %p
      Sie werden
      %strong bei Abstimmungsstart
      benachrichtigt.
    
  - else
    %p
      Um über Neuigkeiten und
      %strong bei Abstimmungsstart benachrichtigt
      zu werden, geben Sie bitte Ihre E-Mail Adresse ein.
    
    = render 'follows/form'
    
    .form_cancel
      = link_to 'Abbrechen', @procedure, class: 'button cancel'
    
  

app/views/procedures/result.html.haml
- h_title "Meinungsbild - #{@procedure.title}"
- h_titlebar_icon 'back_arrow', @procedure
- h_titlebar_text 'Meinungsbild'

.small_content.procedure_result
  %h4
    Meinungsbild zum Vorhaben
    %br
    %strong= @procedure.title
  
  - unless @procedure.votes_sum > 0
    %p
      Es sind keine Stimmen eingegangen.
    
  - else
    .result_graph
      .labels
        - Procedure::RESULT_KINDS.each do |kind|
          - width = @procedure.relative_votes_for( kind )
          - if width > 0
            .block{ class: kind }= "#{width}%"
          
        
      .blocks
        - Procedure::RESULT_KINDS.each do |kind|
          - width = @procedure.relative_votes_for( kind )
          - if width > 0
            .block{ class: kind, style: "width: #{width*0.97}%;" }
              - if width > 12
                = "#{width}%"
              - else
                &nbsp;
              
            
          
        
      
    
    %table
      - Procedure::RESULT_KINDS.each do |kind|
        %tr
          %td
            =t "labels.#{kind}"
            \:
          
          %td.absolute
            = @procedure.votes_for( kind )
          
          %td.relative
            = "#{@procedure.relative_votes_for( kind )}%"
          
        
      
    
  %br
  .actions
    = link_to 'Zurück', @procedure, class: 'button'
  

app/views/procedures/show.html.haml
- h_title "#{t '.procedure_name'}: #{@procedure.title}"
- h_description @procedure.description || @procedure.abstract
- h_titlebar_icon 'back_arrow', body_path( @procedure.body ) + "##{@procedure.iid}", 'Gremium'
- h_titlebar_text t( '.procedure_name' )

- unless h_visitor_saw? 'procedure_intro'
  - content_for :dialog_content do
    %p
      =t '.dialog_where'
      - if h_for_body? @procedure
        des
        = @procedure.body.name
      
    
  
  - content_for :dialog_actions do
    = link_to t( '.whats_going' ), intro_what_procedure_path( @procedure, saw: :procedure_intro ), class: 'button'
    = link_to t( '.short_intro' ), intro_views_procedure_path( @procedure, saw: :procedure_intro ), class: 'button'
    = link_to t( '.no_thanks' ), procedure_path( @procedure, saw: :procedure_intro ), class: 'button cancel'
  
  = render 'general/dialog', show_after: 45

%section.procedure
  = render 'show_procedure', procedure: @procedure

%section.all_arguments
  = render 'show_arguments', procedure: @procedure

= render 'vote_area', procedure: @procedure