config/routes.rb
Rails.application.routes.draw do
  
  # --- API ------------------------------------
  
  namespace :api_v1 do
    resources :procedures do
      member do
        get :arguments_combined
      end
    end
  end
  
  # --- WEB ------------------------------------
  
  resources :exports
  
  resources :receipts
  get 're/:id' => 'receipts#edit', as: 'answer_receipt'
  
  resources :ratings do
    member do
      put :relay
    end
  end
  get 'ra/:id' => 'ratings#answer', as: 'answer_rating'
  
  resources :follows
  
  resources :favs
  
  resources :comments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :ratings
  end
  
  resources :arguments do
    member do
      put :fav
      put :unfav
      put :approve
    end
    
    resources :comments
    resources :ratings
  end
  
  resources :attachments
  
  resources :procedures do
    member do
      put :activate
      put :approve
      get :intro_what
      get :intro_views
      get :intro_actions
      get :vote
      get :result
      get :embed
    end
    
    resources :attachments
    resources :arguments
    resources :follows
    
    resources :receipts
    
    resources :exports
  end
  
  resources :periods
  
  resources :bodies do
    member do
      get :graph
    end
    
    resources :procedures do
      collection do
        get :coming
        get :most_contributed
        get :most_faved
      end
    end
    resources :subjectgroups do
      resources :procedures
    end
  end
  
  resources :moderatorships
  
  resources :visitors do
    member do
      put :send_confirmation
      get :confirm
    end
    
    resource :account
    resources :arguments
    resources :comments
    resources :favs
    resources :follows
    resources :ratings
  end
  get 'lo/:id' => 'visitors#login', as: 'login_visitor'
  
  resources :accounts do
    member do
      get :set_password
    end
  end
  
  controller :info do
    get 'info/impressum', to: redirect( 'https://gremien.teilt-mit.de/info/impressum' )
    get 'info/datenschutz', to: redirect( 'https://gremien.teilt-mit.de/info/datenschutz' )
    get 'info/details', to: redirect( 'https://gremien.teilt-mit.de/info/details' )
    
    get :cockpit
    get :history
    get :approval
    get :contribution_rules
    get :why
    put :close_dialog
    get 'info/tick_moderation' => 'info#tick_moderation'
    
    get 'info/logs' => 'info#logs'
    
    get 'info/:id' => :show
  end
  
  
  
  # --- Login / Logout Requests ----------------
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  put '/reset_password', to: 'accounts#reset_password'
  
  # --- Log ------------------------------------
  
  resources :logs
  
  # Redirect existing gremieninfo posts
  get '/posts/:id', to: redirect( "https://gremien.teilt-mit.de/posts/%{id}" )
  
  # Redirect unsubscriptions tu gremien.teilt-mit.de
  get '/newssubscriptions/*other', to: redirect { |pp, req| req.original_url.to_s.gsub( '//teilt', '//gremien.teilt' ) }
  
  get '/help', to: 'application#help'
  
  get '/logout', to: 'application#logout'
  
  root to: 'application#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/exports/_form.html.haml
= form_for [ @procedure, export ] do |f|
  - if export.errors.any?
    #error_explanation
      %h2
        = export.errors.count
        Fehler verhindern, dass dieses Mitwirkungsforum erzeugt werden kann:"
      %ul
        - export.errors.full_messages.each do |message|
          %li= message
        
      
    
  
  .field
    = f.check_box :only_faved
    = f.label :only_faved, "Nur <strong>favorisierte</strong> Argumente".html_safe
    .field_explanation Nur von mir favorisierte Argumente exportieren. Damit ist eine gezielte Auswahl möglich.
    
  
  .field
    = f.check_box :hide_voting
    = f.label :hide_voting, "Abstimmen-Taste ausblenden".html_safe
  
  .field
    .form_explanation Welche Spalte soll als erstes anzeigt werden?
    
    = f.radio_button :first_column, 'pro'
    = f.label :first_column, "Pro Argumente".html_safe, value: :pro
    %br
    = f.radio_button :first_column, :info
    = f.label :first_column, "Info Spalte".html_safe, value: :info
    %br
    = f.radio_button :first_column, :contra
    = f.label :first_column, "Contra Argumente".html_safe, value: :contra
  
  .actions
    = f.submit t( 'actions.save' ), class: 'button'
  

app/views/exports/_show_arguments.html.haml
- # --------------------------------------------
- procedure = export.procedure
- pros = h_args( procedure, 'pro' )
- infos = h_args( procedure, 'info' )
- contras = h_args( procedure, 'contra' )

- if export.account and export.account.visitor
  - visitor = export.account.visitor
  - pros_show = pros.select { |a| a.faved_by?( visitor ) and a.fav_for( visitor ).up? }
  - infos_show = infos.select { |a| a.faved_by?( visitor ) and a.fav_for( visitor ).up? }
  - contras_show = contras.select { |a| a.faved_by?( visitor ) and a.fav_for( visitor ).up? }
- else
  - pros_show = pros
  - infos_show = infos
  - contras_show = contras

- unless export.first_column.blank?
  - active_column = export.first_column
- else
  - active_column = 'info'
  - if infos.size < 1
    - active_column = 'contra' if contras.size > 0
    - active_column = 'pro' if pros.size > 0 and pros.size >= contras.size
  


%nav.arguments_nav
  .nav_column.pro{ class: active_column == 'pro' ? 'active' : nil, data: { kind: 'pro' } }
    = pros.size
    =t 'labels.pro'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'pro' ), class: 'button_plus', target: '_blank'
  
  .nav_column.info{ class: active_column == 'info' ? 'active' : nil, data: { kind: 'info' } }
    = infos.size
    =t 'labels.info'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'info' ), class: 'button_plus', target: '_blank'
  
  .nav_column.contra{ class: active_column == 'contra' ? 'active' : nil, data: { kind: 'contra' } }
    = contras.size
    =t 'labels.contra'
    = link_to image_tag( 'sym/plus_w100.svg' ), new_procedure_argument_path( procedure, kind: 'contra' ), class: 'button_plus', target: '_blank'
  

.arguments_columns
  .arguments_column.pro{ class: active_column == 'pro' ? 'active' : nil, data: { kind: 'pro' } }
    - if pros.blank?
      .help=t '.new_pro_arg'
      
    - else
      - unless export.only_faved?
        = render 'arguments/arguments_list', arguments: pros, initially_closed: true
      - else
        = render 'arguments/arguments_list', arguments: pros_show, initially_closed: true
        - if pros.size > pros_show.size
          .column_link
            zu
            = link_to 'diesem Vorhaben', procedure, target: '_blank'
            gibt es
            %br
            in PRO noch
            = pluralize( pros.size - pros_show.size, 'Argument' ) + '...'
          
        
      
    
  
  .arguments_column.info{ class: active_column == 'info' ? 'active' : nil, data: { kind: 'info' } }
    - if infos.blank?
      .help=t '.new_info_arg'

    - else
      - unless export.only_faved?
        = render 'arguments/arguments_list', arguments: infos, initially_closed: true
      - else
        = render 'arguments/arguments_list', arguments: infos_show, initially_closed: true
        - if infos.size > infos_show.size
          .column_link
            zu
            = link_to 'diesem Vorhaben', procedure, target: '_blank'
            gibt es
            %br
            in INFO noch
            = pluralize( infos.size - infos_show.size, 'Argument' ) + '...'
          
        
      
    
  
  .arguments_column.contra{ class: active_column == 'contra' ? 'active' : nil, data: { kind: 'contra' } }
    - if contras.blank?
      .help=t '.new_contra_arg'

    - else
      - unless export.only_faved?
        = render 'arguments/arguments_list', arguments: contras, initially_closed: true
      - else
        = render 'arguments/arguments_list', arguments: contras_show, initially_closed: true
        - if contras.size > contras_show.size
          .column_link
            zu
            = link_to 'diesem Vorhaben', procedure, target: '_blank'
            gibt es
            %br
            in CONTRA noch
            = pluralize( contras.size - contras_show.size, 'Argument' ) + '...'
          
        
      
    
  

app/views/exports/new.html.haml
- h_title "#{t 'labels.procedure'} #{t 'actions.share_embed'}: #{@export.procedure.title}"
- h_description @export.procedure.description || @procedure.abstract
- h_titlebar_icon 'back_arrow', @export.procedure, t( 'labels.procedure' )
- h_titlebar_text t( 'actions.share_embed' )

.entity_form
  %h4 Vorhaben in Website einbetten
  
  %p
    Verwenden Sie diesen Code-Schnipsel, um das Vorhaben in eine andere Website einzubetten.
  
  .embed_code
    = '<iframe src="' + root_url + 'exports/' + @export.export_token + '" width="100%" height="700"></iframe>'
  %br
  %h5 Weitere Optionen
  
  - unless current_account
    %p
      Sie können weitere Optionen für Ihren Export konfigurieren, wenn Sie einen Account haben.
    
    %p
      = link_to 'Account anlegen&nbsp;&rarr;'.html_safe, new_account_path
      &nbsp;&nbsp;oder&nbsp;&nbsp;
      = link_to 'Einloggen&nbsp;&rarr;'.html_safe, login_path
      
    
  - else
    = render 'form', export: @export
  

app/views/exports/not_found.html.haml
- h_title "#{t '.not_found'}: #{params[ :id ]}"
- h_description t( '.not_found_description' )
- h_titlebar_export t( '.not_found' )


.small_content
  %h4= t '.not_found'
  %p= t '.not_found_description'
  %p= link_to "#{t '.link_other'}&nbsp;&rarr;".html_safe, bodies_path, target: '_blank'

app/views/exports/show.html.haml
- h_title "#{t '.procedure_name'}: #{@export.procedure.title}"
- h_description @export.procedure.description || @export.procedure.abstract
- h_titlebar_export "Position von #{@author_name_text}"


%section.procedure
  = render 'procedures/show_procedure', procedure: @export.procedure, with_actions: false, new_tab: true

%section.all_arguments
  = render 'show_arguments', export: @export

= render 'procedures/vote_area', export: @export